### ISSUE TITLE
Navigation arrows on top left not functional

### ISSUE THREAD

**Issue by daxid** [SibrenVasse/deezer#3]
Navigation arrows on top left not functional

**Comment by SibrenVasse** [comment]
Can you verify 9d3e3a65d62eb3c6a320d6628e02f1a2130d4d47 fixes your issue?

**Comment by daxid** [comment]
Wow, that was fast !

I installed the package through Arch AUR. Can you suggest me a way to test your patch ?

By the way, thanks a lot for proposing a solution to Deezer users on Linux.

Are you working for Deezer or something ?

**Comment by SibrenVasse** [comment]
I'm not affiliated with Deezer in any way. ;)

You can try the patch by:

> git clone https://github.com/SibrenVasse/deezer
> cd deezer
> makepkg -si

**Comment by daxid** [comment]
The patch most definitely does the job ! 

Really appreciating your job here. I gess you must at least be affiliated with Deezer as a user/client.

I feel like I abuse of your time but a small readme would be really nice to describe what you are achieving with this work.
My understanding is that the app is not native but that Electron technology allows to use the Windows executable on other platforms... not really sure how it goes.

Anyway, thanks a lot for your work, Deezer should be paying you !

**Comment by SibrenVasse** [comment]
Awesome, I'll close the issue then!
And yes, the only way I'm affiliated with Deezer is as a user.

I shall look a look at a README in the future, but here is a small introduction:

For windows, Deezer distributes a version of the electron run time (older version than arch, platform dependent binary) and the source code of their application itself (which is kind of platform independent~ish).
The build process of this package extracts the application source from the windows installer.
I've been able to patch it up so that it will:
1) run with the newer version of electron shipped with Arch Linux (primarily breaking changes between major electron releases)
2) Patch some platform specific code

Which means you're essentially running the same code as on windows, with the exception of the patches that are in this repository, these are my changes (*.patch files).

I've got the feeling they have been picking / incorporating some of my patches, as the same code / similar changes has been appearing in their source code. I was then able to drop the patch.
Just a feeling though. ;)
